# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Tue Jul  4 17:13:12 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.jobs_tab = QtWidgets.QWidget()
        self.jobs_tab.setObjectName("jobs_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.jobs_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.jobs_tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.running_scroll = QtWidgets.QScrollArea(self.splitter)
        self.running_scroll.setWidgetResizable(True)
        self.running_scroll.setObjectName("running_scroll")
        self.running_w = QtWidgets.QWidget()
        self.running_w.setGeometry(QtCore.QRect(0, 0, 762, 312))
        self.running_w.setObjectName("running_w")
        self.running_scroll.setWidget(self.running_w)
        self.pending_scroll = QtWidgets.QScrollArea(self.splitter)
        self.pending_scroll.setWidgetResizable(True)
        self.pending_scroll.setObjectName("pending_scroll")
        self.pendding_w = QtWidgets.QWidget()
        self.pendding_w.setGeometry(QtCore.QRect(0, 0, 762, 178))
        self.pendding_w.setObjectName("pendding_w")
        self.pending_scroll.setWidget(self.pendding_w)
        self.verticalLayout.addWidget(self.splitter)
        self.tabWidget.addTab(self.jobs_tab, "")
        self.hosts_tab = QtWidgets.QWidget()
        self.hosts_tab.setObjectName("hosts_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.hosts_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.hosts_tab)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.tabWidget.addTab(self.hosts_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRescedule = QtWidgets.QAction(MainWindow)
        self.actionRescedule.setObjectName("actionRescedule")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSuspend = QtWidgets.QAction(MainWindow)
        self.actionSuspend.setObjectName("actionSuspend")
        self.actionResume = QtWidgets.QAction(MainWindow)
        self.actionResume.setObjectName("actionResume")
        self.actionHold = QtWidgets.QAction(MainWindow)
        self.actionHold.setObjectName("actionHold")
        self.menuSettings.addAction(self.actionSettings)
        self.menuControl.addAction(self.actionRescedule)
        self.menuControl.addAction(self.actionDelete)
        self.menuControl.addAction(self.actionSuspend)
        self.menuControl.addAction(self.actionResume)
        self.menuControl.addAction(self.actionHold)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jobs_tab), QtWidgets.QApplication.translate("MainWindow", "Jobs", None, -1))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Hostname", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hosts_tab), QtWidgets.QApplication.translate("MainWindow", "Hosts", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Main", None, -1))
        self.menuControl.setTitle(QtWidgets.QApplication.translate("MainWindow", "Control", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.actionRescedule.setText(QtWidgets.QApplication.translate("MainWindow", "Rescedule", None, -1))
        self.actionDelete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.actionSuspend.setText(QtWidgets.QApplication.translate("MainWindow", "Suspend", None, -1))
        self.actionResume.setText(QtWidgets.QApplication.translate("MainWindow", "Resume", None, -1))
        self.actionHold.setText(QtWidgets.QApplication.translate("MainWindow", "Hold", None, -1))

